title: A blog with Github Pages
author: Wes Oler
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A simple blog example on Github Pages 
theme: minima

# social links 
twitter_username: 
github_username:  wes-o

show_excerpts: true # set to false to remove excerpts on the homepage
